pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=validate"
    actions:
      merge:
        method: merge
